# Generated by Django 3.1 on 2020-08-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savestpages', '0002_auto_20200826_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SavestUser',
        ),
    ]
