# Generated by Django 3.1 on 2020-08-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savestpages', '0003_auto_20200827_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savestuser',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
