# Generated by Django 3.1 on 2020-08-27 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('savestpages', '0004_auto_20200827_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savestuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
