# Generated by Django 3.1 on 2020-08-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savestpages', '0005_auto_20200827_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savestuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
