# Generated by Django 3.1 on 2020-08-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savestpages', '0006_auto_20200827_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='savestuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
